### ISSUE TITLE
Put the glyph's phoneme in the list of possible answers

### ISSUE THREAD

**Issue by Qix-** [MichalPaszkiewicz/hieroglyph#1]
There's one thing that almost hurt my ability to remember the glyphs - after a while, I forgot some of the phonemes that belonged to some of the characters.

Perhaps in the list of multiple choice answers, you could include, for instance, `Aleph (a)`.

**Comment by MichalPaszkiewicz** [comment]
Good idea! :)

**Comment by MichalPaszkiewicz** [comment]
I've added them in. Please however be aware, that Egyptologists are unsure as to what the exact phonemes were for each of the characters, so most phonemes are just guesstimates. The characters I'm displaying are actually the computer symbols (but will let you at least find a way to vocalise the characters with characters you already know). 

I've added the characters to the biliteral section as well (although I have a feeling not many people will get that far).

**Comment by Qix-** [comment]
Good to know :D Thank you very much
